app = 'dura-api-minimal'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = "Dockerfile.minimal"

[env]
  PORT = '8080'
  FLASK_APP = 'app.py'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512 