# fly.toml app configuration file generated for dura-app on 2025-04-07T13:14:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dura-app'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
